-- Run this entire script once in Supabase -> SQL Editor.
-- The Flask app uses the service-role key only on the server.

create table if not exists public.users (
    id bigint generated by default as identity primary key,
    username text not null unique,
    password_hash text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.diary_entries (
    id bigint generated by default as identity primary key,
    username text not null,
    entry_date text not null,
    entry_text text not null,
    created_at timestamptz not null default now()
);

create table if not exists public.reminders (
    id bigint generated by default as identity primary key,
    username text not null,
    reminder_date date not null,
    reminder_time time not null,
    created_at timestamptz not null default now()
);

create table if not exists public.calculations (
    id bigint generated by default as identity primary key,
    username text not null,
    expression text not null,
    result text not null,
    created_at timestamptz not null default now()
);

-- RLS is enabled so the public API key cannot directly read/write these tables.
-- The Flask server uses SUPABASE_SERVICE_ROLE_KEY, which bypasses RLS.
alter table public.users enable row level security;
alter table public.diary_entries enable row level security;
alter table public.reminders enable row level security;
alter table public.calculations enable row level security;
